#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Spidola contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Fail closed on SwiftPM license drift and render the reviewed notices resource."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_RESOLVED = ROOT / "apps/tvos/Packages/PlayerMPV/Package.resolved"
DEFAULT_CHECKOUTS = ROOT / "apps/tvos/Packages/PlayerMPV/.build/checkouts"
DEFAULT_POLICY = ROOT / "tools/licenses/swiftpm-policy.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--resolved", type=Path, default=DEFAULT_RESOLVED)
    parser.add_argument("--checkouts", type=Path, default=DEFAULT_CHECKOUTS)
    parser.add_argument("--policy", type=Path, default=DEFAULT_POLICY)
    parser.add_argument("--notice-output", type=Path)
    parser.add_argument(
        "--check-notice",
        action="store_true",
        help="fail instead of updating a stale --notice-output",
    )
    return parser.parse_args()


def fail(message: str) -> None:
    print(f"swiftpm-license-gate: {message}", file=sys.stderr)
    raise SystemExit(1)


def load_json(path: Path) -> object:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        fail(f"cannot read {path}: {error}")


def find_checkout(checkouts: Path, identity: str) -> Path:
    if not checkouts.is_dir():
        fail(f"missing SwiftPM checkouts at {checkouts}; run swift package resolve first")
    matches = [path for path in checkouts.iterdir() if path.is_dir() and path.name.lower() == identity]
    if len(matches) != 1:
        fail(f"expected one checkout for {identity}, found {len(matches)} under {checkouts}")
    return matches[0]


def render_notice(reviewed: list[tuple[dict[str, str], str]]) -> str:
    lines = [
        "THIRD-PARTY NOTICES",
        "",
        "Generated by tools/licenses/check-swiftpm-licenses.py from the resolved, reviewed graph.",
        "Do not edit this file by hand.",
    ]
    for package, license_text in sorted(reviewed, key=lambda item: item[0]["name"].lower()):
        lines.extend(
            [
                "",
                "=" * 78,
                f'{package["name"]} {package["version"]}',
                f'Source: {package["location"]}',
                f'License: {package["license"]}',
                "=" * 78,
                "",
                license_text.rstrip(),
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    policy = load_json(args.policy)
    resolved = load_json(args.resolved)
    if not isinstance(policy, dict) or not isinstance(resolved, dict):
        fail("policy and Package.resolved must contain JSON objects")

    allowed = set(policy.get("allowedSpdx", []))
    configured = policy.get("packages", [])
    pins = resolved.get("pins", [])
    if not isinstance(configured, list) or not isinstance(pins, list):
        fail("policy packages and Package.resolved pins must contain arrays")

    policy_by_identity = {package["identity"]: package for package in configured}
    pins_by_identity = {pin["identity"]: pin for pin in pins}
    if set(policy_by_identity) != set(pins_by_identity):
        added = sorted(set(pins_by_identity) - set(policy_by_identity))
        removed = sorted(set(policy_by_identity) - set(pins_by_identity))
        fail(f"resolved graph differs from policy (unreviewed={added}, missing={removed})")

    reviewed: list[tuple[dict[str, str], str]] = []
    for identity, package in policy_by_identity.items():
        pin = pins_by_identity[identity]
        state = pin.get("state", {})
        for field, actual in (
            ("location", pin.get("location")),
            ("version", state.get("version")),
            ("revision", state.get("revision")),
        ):
            if actual != package[field]:
                fail(f"{identity} {field} is {actual!r}; reviewed value is {package[field]!r}")

        license_id = package["license"]
        if license_id not in allowed:
            fail(f"{identity} declares disallowed SPDX license {license_id}")

        checkout = find_checkout(args.checkouts, identity)
        license_path = checkout / package["licenseFile"]
        try:
            license_bytes = license_path.read_bytes()
        except OSError as error:
            fail(f"cannot read {license_path}: {error}")
        digest = hashlib.sha256(license_bytes).hexdigest()
        if digest != package["licenseSha256"]:
            fail(
                f"{identity} license text changed ({digest}); review it and update the policy deliberately"
            )
        reviewed.append((package, license_bytes.decode("utf-8")))

    if args.notice_output:
        expected = render_notice(reviewed)
        actual = args.notice_output.read_text(encoding="utf-8") if args.notice_output.exists() else None
        if args.check_notice:
            if actual != expected:
                fail(f"{args.notice_output} is stale; regenerate it without --check-notice")
        elif actual != expected:
            args.notice_output.parent.mkdir(parents=True, exist_ok=True)
            args.notice_output.write_text(expected, encoding="utf-8")

    print(f"swiftpm-license-gate: {len(reviewed)} reviewed package(s), all licenses allowed")


if __name__ == "__main__":
    main()
